//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeProduct_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public int productId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string img { get; set; }
        public string description { get; set; }
    }
}
