//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeProduct_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewMaster
    {
        public int reviewId { get; set; }
        public Nullable<int> reviewTypeId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> siteId { get; set; }
        public Nullable<int> rating { get; set; }
        public string review { get; set; }
        public Nullable<System.DateTime> addedDate { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<int> productId { get; set; }
    }
}
