//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeProduct_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentiWordNet
    {
        public int SentiId { get; set; }
        public string pos { get; set; }
        public string Id { get; set; }
        public Nullable<decimal> PosScore { get; set; }
        public Nullable<decimal> NegScore { get; set; }
        public string SynsetTerms { get; set; }
    }
}
